name: Publish Python Package
on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    uses: synodic-software/.github/.github/workflows/python-publish.yml@stable
    with:
      repository_url: https://upload.pypi.org/legacy/
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
