name: Python Docs

on:
  workflow_call:

jobs:
  pypi_development_deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.4.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'

      - name: Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true' # Only run if the cache is old
        run: poetry install --no-interaction -E examples

      - name: Build Documentation
        run: poetry run invoke docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: docs/_build

