name: Python Publish

on:
  workflow_call:
    inputs:
      repository_url:
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true
jobs:
  pypi_release_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.4.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'

      - name: Build
        run: poetry build

      - name: Publish
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ inputs.repository_url }}
